# We can define Zizmor Rules which should be default for all workflows here.
# https://docs.zizmor.sh/
rules:
  unpinned-uses:
    config:
      policies:
        KvalitetsIT/*: any # trust KvalitetsIT
